### ISSUE TITLE
Fix compatibility with sunpy>=3.1

### ISSUE THREAD

**Issue by wtbarnes** [USNavalResearchLaboratory/eispac#38]
Is there a reason to pin `sunpy<3.1`? Is there something in the latest release that breaks something in eispac?

**Comment by MJWeberg** [comment]
Yes, the tests were failing with ndcube v1.4.2 and sunpy v3.1 due to some underlying change in the plotting methods _somewhere_ in the chain. I have not to had a chance to fully diagnose the issue since I am still testing a workaround for the changes in NDCube v2.0, but I should hopefully have a patch ready later today or maybe tomorrow.

**Comment by MJWeberg** [comment]
Mostly fixed in NDCube patch (#40). There is still a warning that test_eismap expects to see that is not being issued in SunPy 3.1. For now, I just disabled the check for the warning, but kept the actual test case. Shall we consider this issue closed for now, or should we follow up on the missing warning first?

**Comment by wtbarnes** [comment]
I'll try to deal with that test in #39.
