### ISSUE TITLE
'width' keyword in the EISMap object

### ISSUE THREAD

**Issue by MohamedNedal** [USNavalResearchLaboratory/eispac#79]
I have two questions please:
1) the EISMap for the measurement `width`. What does the `width` map represent in this context?
2) How can I get the exposure time over which these maps are estimated (eg. start and end time, as well as the time cadence)?

![image](https://github.com/USNavalResearchLaboratory/eispac/assets/43330567/3d0e09c1-016a-4779-a548-4e75701f95c0)

**Comment by MJWeberg** [comment]
Hello, 
Thanks for using EISPAC! 

1. The `width` returned by the fitting routine is defined as the standard deviation of the Gaussian function used to fit the spectral line. In spectroscopy this is commonly referred to as the "spectral" or "line" width. The equation for each component of the multi-Gaussian fit is given in the note at the bottom of following section of the online documentation: https://eispac.readthedocs.io/en/latest/guide/04-fitting.html#loading-fit-templates

2. Timing information is contained in the `.meta` dictionary of both the `EISCube` and `EISFitResult` objects. In particular, `.meta['date_obs']` and `.meta['duration']` contain arrays of, respectively, the start times (in UTC) and exposure lengths (in [s]) for each raster step in the image. **Please note:** since EIS always steps through the raster positions from solar west to east (i.e. right to left in the images), the first array element in the `date_obs` and `duration` arrays corresponds to the LAST raster position and the last array elements give the values for the FIRST raster position.

Sorry if this was not clear in the documentation. When we next update the docs, we will be sure add a section with more details about the timing and exposure information.

Thanks for your questions! I will leave this issue open for a few days, in case you have any follow-up questions. If you have additional questions about EIS or the code unrelated to the widths or timing, please feel to open a new issue (so as to make searching the issues easier in the future).

**Comment by MohamedNedal** [comment]
Thank you so much @MJWeberg 
If I may ask another question, I was wondering what is the difference between the Doppler velocity maps and the non-thermal velocity? and how can I extract the non-velocity maps using the eispac?
Here's an example from [this paper](https://www.aanda.org/articles/aa/abs/2021/06/aa39514-20/aa39514-20.html) in which they used the EIS data
![image](https://github.com/USNavalResearchLaboratory/eispac/assets/43330567/32f89afc-2096-4244-87e2-16ca38e04b65)
